// generated by cdktf get
// Azure/avm-res-containerregistry-registry/azurerm
import { TerraformModule, TerraformModuleUserConfig } from 'cdktf';
import { Construct } from 'constructs';
export interface ContainerregistryConfig extends TerraformModuleUserConfig {
  /**
  * Specifies whether the admin user is enabled. Defaults to `false`.
  */
  readonly adminEnabled?: boolean;
  /**
  * Specifies whether anonymous (unauthenticated) pull access to this Container Registry is allowed.  Requries Standard or Premium SKU.
  */
  readonly anonymousPullEnabled?: boolean;
  /**
  * A map of diagnostic settings to create on the Key Vault. The map key is deliberately arbitrary to avoid issues where map keys maybe unknown at plan time.
Controls the Customer managed key configuration on this resource. The following properties can be specified:
- `key_vault_resource_id` - (Required) Resource ID of the Key Vault that the customer managed key belongs to.
- `key_name` - (Required) Specifies the name of the Customer Managed Key Vault Key.
- `key_version` - (Optional) The version of the Customer Managed Key Vault Key.
- `user_assigned_identity` - (Optional) The User Assigned Identity that has access to the key.
  - `resource_id` - (Required) The resource ID of the User Assigned Identity that has access to the key.

  */
  readonly customerManagedKey?: any;
  /**
  * Specifies whether to enable dedicated data endpoints for this Container Registry.  Requires Premium SKU.
  */
  readonly dataEndpointEnabled?: boolean;
  /**
  *   A map of diagnostic settings to create on the Container Registry. The map key is deliberately arbitrary to avoid issues where map keys maybe unknown at plan time.
  
  - `name` - (Optional) The name of the diagnostic setting. One will be generated if not set, however this will not be unique if you want to create multiple diagnostic setting resources.
  - `log_categories` - (Optional) A set of log categories to send to the log analytics workspace. Defaults to `[]`.
  - `log_groups` - (Optional) A set of log groups to send to the log analytics workspace. Defaults to `["allLogs"]`.
  - `metric_categories` - (Optional) A set of metric categories to send to the log analytics workspace. Defaults to `["AllMetrics"]`.
  - `log_analytics_destination_type` - (Optional) The destination type for the diagnostic setting. Possible values are `Dedicated` and `AzureDiagnostics`. Defaults to `Dedicated`.
  - `workspace_resource_id` - (Optional) The resource ID of the log analytics workspace to send logs and metrics to.
  - `storage_account_resource_id` - (Optional) The resource ID of the storage account to send logs and metrics to.
  - `event_hub_authorization_rule_resource_id` - (Optional) The resource ID of the event hub authorization rule to send logs and metrics to.
  - `event_hub_name` - (Optional) The name of the event hub. If none is specified, the default event hub will be selected.
  - `marketplace_partner_resource_id` - (Optional) The full ARM resource ID of the Marketplace resource to which you would like to send Diagnostic LogsLogs.

  * [object Object]
  */
  readonly diagnosticSettings?: any;
  /**
  * This variable controls whether or not telemetry is enabled for the module.
For more information see https://aka.ms/avm/telemetryinfo.
If it is set to false, then no telemetry will be collected.

  * true
  */
  readonly enableTelemetry?: boolean;
  /**
  * Specified whether trust policy is enabled for this Container Registry.
  */
  readonly enableTrustPolicy?: boolean;
  /**
  * Specifies whether export policy is enabled. Defaults to true. In order to set it to false, make sure the public_network_access_enabled is also set to false.
  * true
  */
  readonly exportPolicyEnabled?: boolean;
  /**
  * A list of geo-replication configurations for the Container Registry.

- `location` - (Required) The geographic location where the Container Registry should be geo-replicated.
- `regional_endpoint_enabled` - (Optional) Enables or disables regional endpoint. Defaults to `true`.
- `zone_redundancy_enabled` - (Optional) Enables or disables zone redundancy. Defaults to `true`.
- `tags` - (Optional) A map of additional tags for the geo-replication configuration. Defaults to `null`.


  * 
  */
  readonly georeplications?: any;
  /**
  * Azure region where the resource should be deployed.
  */
  readonly location: string;
  /**
  * Controls the Resource Lock configuration for this resource. The following properties can be specified:

- `kind` - (Required) The type of lock. Possible values are `\"CanNotDelete\"` and `\"ReadOnly\"`.
- `name` - (Optional) The name of the lock. If not specified, a name will be generated based on the `kind` value. Changing this forces the creation of a new resource.

  */
  readonly lock?: any;
  /**
  * Controls the Managed Identity configuration on this resource. The following properties can be specified:

- `system_assigned` - (Optional) Specifies if the System Assigned Managed Identity should be enabled.
- `user_assigned_resource_ids` - (Optional) Specifies a list of User Assigned Managed Identity resource IDs to be assigned to this resource.

  * [object Object]
  */
  readonly managedIdentities?: any;
  /**
  * The name of the Container Registry.
  */
  readonly name: string;
  /**
  * Specifies whether to allow trusted Azure services access to a network restricted Container Registry.
Possible values are `None` and `AzureServices`. Defaults to `None`.

  * None
  */
  readonly networkRuleBypassOption?: string;
  /**
  * The network rule set configuration for the Container Registry.
Requires Premium SKU.

- `default_action` - (Optional) The default action when no rule matches. Possible values are `Allow` and `Deny`. Defaults to `Deny`.
- `ip_rules` - (Optional) A list of IP rules in CIDR format. Defaults to `[]`.
  - `action` - Only "Allow" is permitted
  - `ip_range` - The CIDR block from which requests will match the rule.


  */
  readonly networkRuleSet?: any;
  /**
  * A map of private endpoints to create on the Container Registry. The map key is deliberately arbitrary to avoid issues where map keys maybe unknown at plan time.

- `name` - (Optional) The name of the private endpoint. One will be generated if not set.
- `role_assignments` - (Optional) A map of role assignments to create on the private endpoint. The map key is deliberately arbitrary to avoid issues where map keys maybe unknown at plan time. See `var.role_assignments` for more information.
  - `role_definition_id_or_name` - The ID or name of the role definition to assign to the principal.
  - `principal_id` - The ID of the principal to assign the role to.
  - `description` - (Optional) The description of the role assignment.
  - `skip_service_principal_aad_check` - (Optional) If set to true, skips the Azure Active Directory check for the service principal in the tenant. Defaults to false.
  - `condition` - (Optional) The condition which will be used to scope the role assignment.
  - `condition_version` - (Optional) The version of the condition syntax. Leave as `null` if you are not using a condition, if you are then valid values are '2.0'.
  - `delegated_managed_identity_resource_id` - (Optional) The delegated Azure Resource Id which contains a Managed Identity. Changing this forces a new resource to be created. This field is only used in cross-tenant scenario.
  - `principal_type` - (Optional) The type of the `principal_id`. Possible values are `User`, `Group` and `ServicePrincipal`. It is necessary to explicitly set this attribute when creating role assignments if the principal creating the assignment is constrained by ABAC rules that filters on the PrincipalType attribute.
- `lock` - (Optional) The lock level to apply to the private endpoint. Default is `None`. Possible values are `None`, `CanNotDelete`, and `ReadOnly`.
  - `kind` - (Required) The type of lock. Possible values are `\"CanNotDelete\"` and `\"ReadOnly\"`.
  - `name` - (Optional) The name of the lock. If not specified, a name will be generated based on the `kind` value. Changing this forces the creation of a new resource.
- `tags` - (Optional) A mapping of tags to assign to the private endpoint.
- `subnet_resource_id` - The resource ID of the subnet to deploy the private endpoint in.
- `private_dns_zone_group_name` - (Optional) The name of the private DNS zone group. One will be generated if not set.
- `private_dns_zone_resource_ids` - (Optional) A set of resource IDs of private DNS zones to associate with the private endpoint. If not set, no zone groups will be created and the private endpoint will not be associated with any private DNS zones. DNS records must be managed external to this module.
- `application_security_group_resource_ids` - (Optional) A map of resource IDs of application security groups to associate with the private endpoint. The map key is deliberately arbitrary to avoid issues where map keys maybe unknown at plan time.
- `private_service_connection_name` - (Optional) The name of the private service connection. One will be generated if not set.
- `network_interface_name` - (Optional) The name of the network interface. One will be generated if not set.
- `location` - (Optional) The Azure location where the resources will be deployed. Defaults to the location of the resource group.
- `resource_group_name` - (Optional) The resource group where the resources will be deployed. Defaults to the resource group of the Container Registry.
- `ip_configurations` - (Optional) A map of IP configurations to create on the private endpoint. If not specified the platform will create one. The map key is deliberately arbitrary to avoid issues where map keys maybe unknown at plan time.
  - `name` - The name of the IP configuration.
  - `private_ip_address` - The private IP address of the IP configuration.

  * [object Object]
  */
  readonly privateEndpoints?: any;
  /**
  * Whether to manage private DNS zone groups with this module. If set to false, you must manage private DNS zone groups externally, e.g. using Azure Policy.
  * true
  */
  readonly privateEndpointsManageDnsZoneGroup?: boolean;
  /**
  * Specifies whether public access is permitted.
  * true
  */
  readonly publicNetworkAccessEnabled?: boolean;
  /**
  * Specifies whether the quarantine policy is enabled.
  */
  readonly quarantinePolicyEnabled?: boolean;
  /**
  * The resource group where the resources will be deployed.
  */
  readonly resourceGroupName: string;
  /**
  * If enabled, this retention policy will purge an untagged manifest after a specified number of days.

- `days` - (Optional) The number of days before the policy Defaults to 7 days.


  * 7
  */
  readonly retentionPolicyInDays?: number;
  /**
  * A map of role assignments to create on the <RESOURCE>. The map key is deliberately arbitrary to avoid issues where map keys maybe unknown at plan time.

- `role_definition_id_or_name` - The ID or name of the role definition to assign to the principal.
- `principal_id` - The ID of the principal to assign the role to.
- `description` - (Optional) The description of the role assignment.
- `skip_service_principal_aad_check` - (Optional) If set to true, skips the Azure Active Directory check for the service principal in the tenant. Defaults to false.
- `condition` - (Optional) The condition which will be used to scope the role assignment.
- `condition_version` - (Optional) The version of the condition syntax. Leave as `null` if you are not using a condition, if you are then valid values are '2.0'.
- `delegated_managed_identity_resource_id` - (Optional) The delegated Azure Resource Id which contains a Managed Identity. Changing this forces a new resource to be created. This field is only used in cross-tenant scenario.
- `principal_type` - (Optional) The type of the `principal_id`. Possible values are `User`, `Group` and `ServicePrincipal`. It is necessary to explicitly set this attribute when creating role assignments if the principal creating the assignment is constrained by ABAC rules that filters on the PrincipalType attribute.

> Note: only set `skip_service_principal_aad_check` to true if you are assigning a role to a service principal.

  * [object Object]
  */
  readonly roleAssignments?: any;
  /**
  * The SKU name of the Container Registry. Default is `Premium`. `Possible values are `Basic`, `Standard` and `Premium`.
  * Premium
  */
  readonly sku?: string;
  /**
  * (Optional) Tags of the resource.
  * The property type contains a map, they have special handling, please see {@link cdk.tf/module-map-inputs the docs}
  */
  readonly tags?: { [key: string]: string };
  /**
  * Specifies whether zone redundancy is enabled.  Modifying this forces a new resource to be created.
  * true
  */
  readonly zoneRedundancyEnabled?: boolean;
}
/**
* Defines an Containerregistry based on a Terraform module
*
* Docs at Terraform Registry: {@link https://registry.terraform.io/modules/Azure/avm-res-containerregistry-registry/azurerm/0.4.0 Azure/avm-res-containerregistry-registry/azurerm}
*/
export class Containerregistry extends TerraformModule {
  private readonly inputs: { [name: string]: any } = { }
  public constructor(scope: Construct, id: string, config: ContainerregistryConfig) {
    super(scope, id, {
      ...config,
      source: 'Azure/avm-res-containerregistry-registry/azurerm',
      version: '0.4.0',
    });
    this.adminEnabled = config.adminEnabled;
    this.anonymousPullEnabled = config.anonymousPullEnabled;
    this.customerManagedKey = config.customerManagedKey;
    this.dataEndpointEnabled = config.dataEndpointEnabled;
    this.diagnosticSettings = config.diagnosticSettings;
    this.enableTelemetry = config.enableTelemetry;
    this.enableTrustPolicy = config.enableTrustPolicy;
    this.exportPolicyEnabled = config.exportPolicyEnabled;
    this.georeplications = config.georeplications;
    this.location = config.location;
    this.lock = config.lock;
    this.managedIdentities = config.managedIdentities;
    this.name = config.name;
    this.networkRuleBypassOption = config.networkRuleBypassOption;
    this.networkRuleSet = config.networkRuleSet;
    this.privateEndpoints = config.privateEndpoints;
    this.privateEndpointsManageDnsZoneGroup = config.privateEndpointsManageDnsZoneGroup;
    this.publicNetworkAccessEnabled = config.publicNetworkAccessEnabled;
    this.quarantinePolicyEnabled = config.quarantinePolicyEnabled;
    this.resourceGroupName = config.resourceGroupName;
    this.retentionPolicyInDays = config.retentionPolicyInDays;
    this.roleAssignments = config.roleAssignments;
    this.sku = config.sku;
    this.tags = config.tags;
    this.zoneRedundancyEnabled = config.zoneRedundancyEnabled;
  }
  public get adminEnabled(): boolean | undefined {
    return this.inputs['admin_enabled'] as boolean | undefined;
  }
  public set adminEnabled(value: boolean | undefined) {
    this.inputs['admin_enabled'] = value;
  }
  public get anonymousPullEnabled(): boolean | undefined {
    return this.inputs['anonymous_pull_enabled'] as boolean | undefined;
  }
  public set anonymousPullEnabled(value: boolean | undefined) {
    this.inputs['anonymous_pull_enabled'] = value;
  }
  public get customerManagedKey(): any | undefined {
    return this.inputs['customer_managed_key'] as any | undefined;
  }
  public set customerManagedKey(value: any | undefined) {
    this.inputs['customer_managed_key'] = value;
  }
  public get dataEndpointEnabled(): boolean | undefined {
    return this.inputs['data_endpoint_enabled'] as boolean | undefined;
  }
  public set dataEndpointEnabled(value: boolean | undefined) {
    this.inputs['data_endpoint_enabled'] = value;
  }
  public get diagnosticSettings(): any | undefined {
    return this.inputs['diagnostic_settings'] as any | undefined;
  }
  public set diagnosticSettings(value: any | undefined) {
    this.inputs['diagnostic_settings'] = value;
  }
  public get enableTelemetry(): boolean | undefined {
    return this.inputs['enable_telemetry'] as boolean | undefined;
  }
  public set enableTelemetry(value: boolean | undefined) {
    this.inputs['enable_telemetry'] = value;
  }
  public get enableTrustPolicy(): boolean | undefined {
    return this.inputs['enable_trust_policy'] as boolean | undefined;
  }
  public set enableTrustPolicy(value: boolean | undefined) {
    this.inputs['enable_trust_policy'] = value;
  }
  public get exportPolicyEnabled(): boolean | undefined {
    return this.inputs['export_policy_enabled'] as boolean | undefined;
  }
  public set exportPolicyEnabled(value: boolean | undefined) {
    this.inputs['export_policy_enabled'] = value;
  }
  public get georeplications(): any | undefined {
    return this.inputs['georeplications'] as any | undefined;
  }
  public set georeplications(value: any | undefined) {
    this.inputs['georeplications'] = value;
  }
  public get location(): string {
    return this.inputs['location'] as string;
  }
  public set location(value: string) {
    this.inputs['location'] = value;
  }
  public get lock(): any | undefined {
    return this.inputs['lock'] as any | undefined;
  }
  public set lock(value: any | undefined) {
    this.inputs['lock'] = value;
  }
  public get managedIdentities(): any | undefined {
    return this.inputs['managed_identities'] as any | undefined;
  }
  public set managedIdentities(value: any | undefined) {
    this.inputs['managed_identities'] = value;
  }
  public get name(): string {
    return this.inputs['name'] as string;
  }
  public set name(value: string) {
    this.inputs['name'] = value;
  }
  public get networkRuleBypassOption(): string | undefined {
    return this.inputs['network_rule_bypass_option'] as string | undefined;
  }
  public set networkRuleBypassOption(value: string | undefined) {
    this.inputs['network_rule_bypass_option'] = value;
  }
  public get networkRuleSet(): any | undefined {
    return this.inputs['network_rule_set'] as any | undefined;
  }
  public set networkRuleSet(value: any | undefined) {
    this.inputs['network_rule_set'] = value;
  }
  public get privateEndpoints(): any | undefined {
    return this.inputs['private_endpoints'] as any | undefined;
  }
  public set privateEndpoints(value: any | undefined) {
    this.inputs['private_endpoints'] = value;
  }
  public get privateEndpointsManageDnsZoneGroup(): boolean | undefined {
    return this.inputs['private_endpoints_manage_dns_zone_group'] as boolean | undefined;
  }
  public set privateEndpointsManageDnsZoneGroup(value: boolean | undefined) {
    this.inputs['private_endpoints_manage_dns_zone_group'] = value;
  }
  public get publicNetworkAccessEnabled(): boolean | undefined {
    return this.inputs['public_network_access_enabled'] as boolean | undefined;
  }
  public set publicNetworkAccessEnabled(value: boolean | undefined) {
    this.inputs['public_network_access_enabled'] = value;
  }
  public get quarantinePolicyEnabled(): boolean | undefined {
    return this.inputs['quarantine_policy_enabled'] as boolean | undefined;
  }
  public set quarantinePolicyEnabled(value: boolean | undefined) {
    this.inputs['quarantine_policy_enabled'] = value;
  }
  public get resourceGroupName(): string {
    return this.inputs['resource_group_name'] as string;
  }
  public set resourceGroupName(value: string) {
    this.inputs['resource_group_name'] = value;
  }
  public get retentionPolicyInDays(): number | undefined {
    return this.inputs['retention_policy_in_days'] as number | undefined;
  }
  public set retentionPolicyInDays(value: number | undefined) {
    this.inputs['retention_policy_in_days'] = value;
  }
  public get roleAssignments(): any | undefined {
    return this.inputs['role_assignments'] as any | undefined;
  }
  public set roleAssignments(value: any | undefined) {
    this.inputs['role_assignments'] = value;
  }
  public get sku(): string | undefined {
    return this.inputs['sku'] as string | undefined;
  }
  public set sku(value: string | undefined) {
    this.inputs['sku'] = value;
  }
  public get tags(): { [key: string]: string } | undefined {
    return this.inputs['tags'] as { [key: string]: string } | undefined;
  }
  public set tags(value: { [key: string]: string } | undefined) {
    this.inputs['tags'] = value;
  }
  public get zoneRedundancyEnabled(): boolean | undefined {
    return this.inputs['zone_redundancy_enabled'] as boolean | undefined;
  }
  public set zoneRedundancyEnabled(value: boolean | undefined) {
    this.inputs['zone_redundancy_enabled'] = value;
  }
  public get nameOutput() {
    return this.getString('name')
  }
  public get privateEndpointsOutput() {
    return this.getString('private_endpoints')
  }
  public get resourceOutput() {
    return this.getString('resource')
  }
  public get resourceIdOutput() {
    return this.getString('resource_id')
  }
  public get systemAssignedMiPrincipalIdOutput() {
    return this.getString('system_assigned_mi_principal_id')
  }
  protected synthesizeAttributes() {
    return this.inputs;
  }
}
