// generated by cdktf get
// Azure/avm-res-dbforpostgresql-flexibleserver/azurerm
import { TerraformModule, TerraformModuleUserConfig } from 'cdktf';
import { Construct } from 'constructs';
export interface PostgressqlConfig extends TerraformModuleUserConfig {
  /**
  * A map to allow you to set a user or group as the AD administrator for a PostgreSQL Flexible Server.

- `tenant_id` - The Azure Tenant ID. Changing this forces a new resource to be created.
- `object_id` - The object ID of a user, service principal or security group in the Azure Active Directory tenant set as the Flexible Server Admin. Changing this forces a new resource to be created.
- `principal_name` - The name of Azure Active Directory principal. Changing this forces a new resource to be created.
- `principal_type` - The type of Azure Active Directory principal. Possible values are Group, ServicePrincipal and User. Changing this forces a new resource to be created.


  * [object Object]
  */
  readonly adAdministrator?: any;
  /**
  * (Optional) The Administrator login for the PostgreSQL Flexible Server. Required when `create_mode` is `Default` and `authentication.password_auth_enabled` is `true`.
  */
  readonly administratorLogin?: string;
  /**
  * (Optional) The Password associated with the `administrator_login` for the PostgreSQL Flexible Server. Required when `create_mode` is `Default` and `authentication.password_auth_enabled` is `true`.
  */
  readonly administratorPassword?: string;
  /**
  * - `active_directory_auth_enabled` - (Optional)  Whether or not Active Directory authentication is allowed to access the PostgreSQL Flexible Server. Defaults to `false`.
- `password_auth_enabled` - (Optional) Whether or not password authentication is allowed to access the PostgreSQL Flexible Server. Defaults to `true`.
- `tenant_id` - (Optional) The Tenant ID of the Azure Active Directory which is used by the Active Directory authentication. `active_directory_auth_enabled` must be set to `true`.

  */
  readonly authentication?: any;
  /**
  * (Optional) Is the storage auto grow for PostgreSQL Flexible Server enabled? Defaults to `false`.
  */
  readonly autoGrowEnabled?: boolean;
  /**
  * (Optional) The backup retention days for the PostgreSQL Flexible Server. Possible values are between `7` and `35` days.
  */
  readonly backupRetentionDays?: number;
  /**
  * (Optional) The creation mode which can be used to restore or replicate existing servers. Possible values are `Default`, `GeoRestore`, `PointInTimeRestore`, `Replica` and `Update`.
  */
  readonly createMode?: string;
  /**
  * A map describing customer-managed keys to associate with the resource. This includes the following properties:
- `key_vault_key_id` - (Required) The ID of the Key Vault Key..
- `geo_backup_key_vault_key_id` - (Optional) The ID of the geo backup Key Vault Key
- `geo_backup_user_assigned_identity_id` - (Optional) The geo backup user managed identity id for a Customer Managed Key. Should be added with identity_ids
- `primary_user_assigned_identity` - (Optional) Specifies the primary user managed identity id for a Customer Managed Key. Should be added with identity_ids

  */
  readonly customerManagedKey?: any;
  /**
  * - `name` - (Required) Specifies the name of the PostgreSQL Database, which needs [to be a valid PostgreSQL identifier](https://www.postgresql.org/docs/current/static/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS). Changing this forces a new resource to be created.
- `charset` - (Optional)  Specifies the Charset for the PostgreSQL Database, which needs [to be a valid PostgreSQL Charset](https://www.postgresql.org/docs/current/static/multibyte.html). Changing this forces a new resource to be created.
- `collation` - (Optional) Specifies the Collation for the PostgreSQL Database, which needs [to be a valid PostgreSQL Collation](https://www.postgresql.org/docs/current/static/collation.html). Note that Microsoft uses different [notation](https://msdn.microsoft.com/library/windows/desktop/dd373814.aspx)


---
`timeouts` block supports the following:
- `create` - (Defaults to 60 minutes) Used when creating the PostgreSQL Database.
- `delete` - (Defaults to 60 minutes) Used when deleting the PostgreSQL Database.
- `read` - (Defaults to 5 minutes) Used when retrieving the PostgreSQL Database.

  * [object Object]
  */
  readonly databases?: any;
  /**
  * (Optional) The ID of the virtual network subnet to create the PostgreSQL Flexible Server. The provided subnet should not have any other resource deployed in it and this subnet will be delegated to the PostgreSQL Flexible Server, if not already delegated. Changing this forces a new PostgreSQL Flexible Server to be created.
  */
  readonly delegatedSubnetId?: string;
  /**
  * A map of diagnostic settings to create on the Key Vault. The map key is deliberately arbitrary to avoid issues where map keys maybe unknown at plan time.

- `name` - (Optional) The name of the diagnostic setting. One will be generated if not set, however this will not be unique if you want to create multiple diagnostic setting resources.
- `log_categories` - (Optional) A set of log categories to send to the log analytics workspace. Defaults to `[]`.
- `log_groups` - (Optional) A set of log groups to send to the log analytics workspace. Defaults to `["allLogs"]`.
- `metric_categories` - (Optional) A set of metric categories to send to the log analytics workspace. Defaults to `["AllMetrics"]`.
- `log_analytics_destination_type` - (Optional) The destination type for the diagnostic setting. Possible values are `Dedicated` and `AzureDiagnostics`. Defaults to `Dedicated`.
- `workspace_resource_id` - (Optional) The resource ID of the log analytics workspace to send logs and metrics to.
- `storage_account_resource_id` - (Optional) The resource ID of the storage account to send logs and metrics to.
- `event_hub_authorization_rule_resource_id` - (Optional) The resource ID of the event hub authorization rule to send logs and metrics to.
- `event_hub_name` - (Optional) The name of the event hub. If none is specified, the default event hub will be selected.
- `marketplace_partner_resource_id` - (Optional) The full ARM resource ID of the Marketplace resource to which you would like to send Diagnostic LogsLogs.

  * [object Object]
  */
  readonly diagnosticSettings?: any;
  /**
  * This variable controls whether or not telemetry is enabled for the module.
For more information see <https://aka.ms/avm/telemetryinfo>.
If it is set to false, then no telemetry will be collected.

  * true
  */
  readonly enableTelemetry?: boolean;
  /**
  * - `name` - (Optional) The name which should be used for this PostgreSQL Flexible Server Firewall Rule.  
- `start_ip_address` - (Optional) The Start IP Address associated with this PostgreSQL Flexible Server Firewall Rule.  
- `end_ip_address` - (Optional) The End IP Address associated with this PostgreSQL Flexible Server Firewall Rule.   

  * [object Object]
  */
  readonly firewallRules?: any;
  /**
  * (Optional) Is Geo-Redundant backup enabled on the PostgreSQL Flexible Server. Defaults to `false`. Changing this forces a new PostgreSQL Flexible Server to be created.
  */
  readonly geoRedundantBackupEnabled?: boolean;
  /**
  * - `mode` - (Required) The high availability mode for the PostgreSQL Flexible Server. Possible value are `SameZone` or `ZoneRedundant`.
- `standby_availability_zone` - (Optional) Specifies the Availability Zone in which the standby Flexible Server should be located.

  * [object Object]
  */
  readonly highAvailability?: any;
  /**
  * Azure region where the resource should be deployed.
  */
  readonly location: string;
  /**
  * Controls the Resource Lock configuration for this resource. The following properties can be specified:

- `kind` - (Required) The type of lock. Possible values are `\"CanNotDelete\"` and `\"ReadOnly\"`.
- `name` - (Optional) The name of the lock. If not specified, a name will be generated based on the `kind` value. Changing this forces the creation of a new resource.

  */
  readonly lock?: any;
  /**
  * - `day_of_week` - (Optional) The day of week for maintenance window, where the week starts on a Sunday, i.e. Sunday = `0`, Monday = `1`. Defaults to `0`.
- `start_hour` - (Optional) The start hour for maintenance window. Defaults to `0`.
- `start_minute` - (Optional) The start minute for maintenance window. Defaults to `0`.

  * [object Object]
  */
  readonly maintenanceWindow?: any;
  /**
  * Controls the Managed Identity configuration on this resource. The following properties can be specified:

- `system_assigned` - (Optional) Specifies if the System Assigned Managed Identity should be enabled.
- `user_assigned_resource_ids` - (Optional) Specifies a list of User Assigned Managed Identity resource IDs to be assigned to this resource.

  * [object Object]
  */
  readonly managedIdentities?: any;
  /**
  * The name of the this resource.
  */
  readonly name: string;
  /**
  * (Optional) The point in time to restore from `source_server_id` when `create_mode` is `GeoRestore`, `PointInTimeRestore`. Changing this forces a new PostgreSQL Flexible Server to be created.
  */
  readonly pointInTimeRestoreTimeInUtc?: string;
  /**
  * (Optional) The ID of the private DNS zone to create the PostgreSQL Flexible Server.
  */
  readonly privateDnsZoneId?: string;
  /**
  * A map of private endpoints to create on this resource. The map key is deliberately arbitrary to avoid issues where map keys maybe unknown at plan time.

- `name` - (Optional) The name of the private endpoint. One will be generated if not set.
- `role_assignments` - (Optional) A map of role assignments to create on the private endpoint. The map key is deliberately arbitrary to avoid issues where map keys maybe unknown at plan time. See `var.role_assignments` for more information.
- `lock` - (Optional) The lock level to apply to the private endpoint. Default is `None`. Possible values are `None`, `CanNotDelete`, and `ReadOnly`.
- `tags` - (Optional) A mapping of tags to assign to the private endpoint.
- `subnet_resource_id` - The resource ID of the subnet to deploy the private endpoint in.
- `private_dns_zone_group_name` - (Optional) The name of the private DNS zone group. One will be generated if not set.
- `private_dns_zone_resource_ids` - (Optional) A set of resource IDs of private DNS zones to associate with the private endpoint. If not set, no zone groups will be created and the private endpoint will not be associated with any private DNS zones. DNS records must be managed external to this module.
- `application_security_group_resource_ids` - (Optional) A map of resource IDs of application security groups to associate with the private endpoint. The map key is deliberately arbitrary to avoid issues where map keys maybe unknown at plan time.
- `private_service_connection_name` - (Optional) The name of the private service connection. One will be generated if not set.
- `network_interface_name` - (Optional) The name of the network interface. One will be generated if not set.
- `location` - (Optional) The Azure location where the resources will be deployed. Defaults to the location of the resource group.
- `resource_group_name` - (Optional) The resource group where the resources will be deployed. Defaults to the resource group of this resource.
- `ip_configurations` - (Optional) A map of IP configurations to create on the private endpoint. If not specified the platform will create one. The map key is deliberately arbitrary to avoid issues where map keys maybe unknown at plan time.
  - `name` - The name of the IP configuration.
  - `private_ip_address` - The private IP address of the IP configuration.

  * [object Object]
  */
  readonly privateEndpoints?: any;
  /**
  * Whether to manage private DNS zone groups with this module. If set to false, you must manage private DNS zone groups externally, e.g. using Azure Policy.
  * true
  */
  readonly privateEndpointsManageDnsZoneGroup?: boolean;
  /**
  * (Optional) Whether the server is publicly accessible.  Defaults to `false`.
  */
  readonly publicNetworkAccessEnabled?: boolean;
  /**
  * (Optional) The replication role for the PostgreSQL Flexible Server. Possible value is `None`.
  */
  readonly replicationRole?: string;
  /**
  * The resource group where the resources will be deployed.
  */
  readonly resourceGroupName: string;
  /**
  * A map of role assignments to create on this resource. The map key is deliberately arbitrary to avoid issues where map keys maybe unknown at plan time.

- `role_definition_id_or_name` - The ID or name of the role definition to assign to the principal.
- `principal_id` - The ID of the principal to assign the role to.
- `description` - The description of the role assignment.
- `skip_service_principal_aad_check` - If set to true, skips the Azure Active Directory check for the service principal in the tenant. Defaults to false.
- `condition` - The condition which will be used to scope the role assignment.
- `condition_version` - The version of the condition syntax. Valid values are '2.0'.

> Note: only set `skip_service_principal_aad_check` to true if you are assigning a role to a service principal.

  * [object Object]
  */
  readonly roleAssignments?: any;
  /**
  * A map to set a PostgreSQL Configuration value on a Azure PostgreSQL Flexible Server.

- `name` - Specifies the name of the PostgreSQL Configuration, which needs to be a valid PostgreSQL configuration name. Changing this forces a new resource to be created.
- `config` - Specifies the value of the PostgreSQL Configuration. See the PostgreSQL documentation for valid values.


  * [object Object]
  */
  readonly serverConfiguration?: any;
  /**
  * (Optional) The version of PostgreSQL Flexible Server to use. Possible values are `11`,`12`, `13`, `14`, `15` and `16`. Required when `create_mode` is `Default`.
  */
  readonly serverVersion?: string;
  /**
  * (Optional) The SKU Name for the PostgreSQL Flexible Server. The name of the SKU, follows the `tier` + `name` pattern (e.g. `B_Standard_B1ms`, `GP_Standard_D2s_v3`, `MO_Standard_E4s_v3`).
  */
  readonly skuName?: string;
  /**
  * (Optional) The resource ID of the source PostgreSQL Flexible Server to be restored. Required when `create_mode` is `GeoRestore`, `PointInTimeRestore` or `Replica`. Changing this forces a new PostgreSQL Flexible Server to be created.
  */
  readonly sourceServerId?: string;
  /**
  * (Optional) The max storage allowed for the PostgreSQL Flexible Server. Possible values are `32768`, `65536`, `131072`, `262144`, `524288`, `1048576`, `2097152`, `4193280`, `4194304`, `8388608`, `16777216` and `33553408`.
  */
  readonly storageMb?: number;
  /**
  * (Optional) The storage tier for the PostgreSQL Flexible Server. Possible values are `P4`, `P6`, `P10`, `P15`, `P20`, `P30`, `P40`, `P50`, `P60`, `P70` or `P80`.
  */
  readonly storageTier?: string;
  /**
  * (Optional) Tags of the resource.
  * The property type contains a map, they have special handling, please see {@link cdk.tf/module-map-inputs the docs}
  */
  readonly tags?: { [key: string]: string };
  /**
  * - `create` - (Defaults to 1 hour) Used when creating the PostgreSQL Flexible Server.
- `delete` - (Defaults to 1 hour) Used when deleting the PostgreSQL Flexible Server.
- `read` - (Defaults to 5 minutes) Used when retrieving the PostgreSQL Flexible Server.
- `update` - (Defaults to 1 hour) Used when updating the PostgreSQL Flexible Server.

  */
  readonly timeouts?: any;
  /**
  * A map to allow you to create a Virtual Endpoint associated with a Postgres Flexible Replica.

- `name` - (Required) The name of the Virtual Endpoint.
- `replica_server_id` - (Required) The Resource ID of the Replica Postgres Flexible Server this should be associated with.
- `type` - (Required) The type of Virtual Endpoint. Currently only ReadWrite is supported.


  * [object Object]
  */
  readonly virtualEndpoint?: any;
  /**
  * (Optional) Specifies the Availability Zone in which the PostgreSQL Flexible Server should be located.
  */
  readonly zone?: string;
}
/**
* Defines an Postgressql based on a Terraform module
*
* Docs at Terraform Registry: {@link https://registry.terraform.io/modules/Azure/avm-res-dbforpostgresql-flexibleserver/azurerm/0.1.4 Azure/avm-res-dbforpostgresql-flexibleserver/azurerm}
*/
export class Postgressql extends TerraformModule {
  private readonly inputs: { [name: string]: any } = { }
  public constructor(scope: Construct, id: string, config: PostgressqlConfig) {
    super(scope, id, {
      ...config,
      source: 'Azure/avm-res-dbforpostgresql-flexibleserver/azurerm',
      version: '0.1.4',
    });
    this.adAdministrator = config.adAdministrator;
    this.administratorLogin = config.administratorLogin;
    this.administratorPassword = config.administratorPassword;
    this.authentication = config.authentication;
    this.autoGrowEnabled = config.autoGrowEnabled;
    this.backupRetentionDays = config.backupRetentionDays;
    this.createMode = config.createMode;
    this.customerManagedKey = config.customerManagedKey;
    this.databases = config.databases;
    this.delegatedSubnetId = config.delegatedSubnetId;
    this.diagnosticSettings = config.diagnosticSettings;
    this.enableTelemetry = config.enableTelemetry;
    this.firewallRules = config.firewallRules;
    this.geoRedundantBackupEnabled = config.geoRedundantBackupEnabled;
    this.highAvailability = config.highAvailability;
    this.location = config.location;
    this.lock = config.lock;
    this.maintenanceWindow = config.maintenanceWindow;
    this.managedIdentities = config.managedIdentities;
    this.name = config.name;
    this.pointInTimeRestoreTimeInUtc = config.pointInTimeRestoreTimeInUtc;
    this.privateDnsZoneId = config.privateDnsZoneId;
    this.privateEndpoints = config.privateEndpoints;
    this.privateEndpointsManageDnsZoneGroup = config.privateEndpointsManageDnsZoneGroup;
    this.publicNetworkAccessEnabled = config.publicNetworkAccessEnabled;
    this.replicationRole = config.replicationRole;
    this.resourceGroupName = config.resourceGroupName;
    this.roleAssignments = config.roleAssignments;
    this.serverConfiguration = config.serverConfiguration;
    this.serverVersion = config.serverVersion;
    this.skuName = config.skuName;
    this.sourceServerId = config.sourceServerId;
    this.storageMb = config.storageMb;
    this.storageTier = config.storageTier;
    this.tags = config.tags;
    this.timeouts = config.timeouts;
    this.virtualEndpoint = config.virtualEndpoint;
    this.zone = config.zone;
  }
  public get adAdministrator(): any | undefined {
    return this.inputs['ad_administrator'] as any | undefined;
  }
  public set adAdministrator(value: any | undefined) {
    this.inputs['ad_administrator'] = value;
  }
  public get administratorLogin(): string | undefined {
    return this.inputs['administrator_login'] as string | undefined;
  }
  public set administratorLogin(value: string | undefined) {
    this.inputs['administrator_login'] = value;
  }
  public get administratorPassword(): string | undefined {
    return this.inputs['administrator_password'] as string | undefined;
  }
  public set administratorPassword(value: string | undefined) {
    this.inputs['administrator_password'] = value;
  }
  public get authentication(): any | undefined {
    return this.inputs['authentication'] as any | undefined;
  }
  public set authentication(value: any | undefined) {
    this.inputs['authentication'] = value;
  }
  public get autoGrowEnabled(): boolean | undefined {
    return this.inputs['auto_grow_enabled'] as boolean | undefined;
  }
  public set autoGrowEnabled(value: boolean | undefined) {
    this.inputs['auto_grow_enabled'] = value;
  }
  public get backupRetentionDays(): number | undefined {
    return this.inputs['backup_retention_days'] as number | undefined;
  }
  public set backupRetentionDays(value: number | undefined) {
    this.inputs['backup_retention_days'] = value;
  }
  public get createMode(): string | undefined {
    return this.inputs['create_mode'] as string | undefined;
  }
  public set createMode(value: string | undefined) {
    this.inputs['create_mode'] = value;
  }
  public get customerManagedKey(): any | undefined {
    return this.inputs['customer_managed_key'] as any | undefined;
  }
  public set customerManagedKey(value: any | undefined) {
    this.inputs['customer_managed_key'] = value;
  }
  public get databases(): any | undefined {
    return this.inputs['databases'] as any | undefined;
  }
  public set databases(value: any | undefined) {
    this.inputs['databases'] = value;
  }
  public get delegatedSubnetId(): string | undefined {
    return this.inputs['delegated_subnet_id'] as string | undefined;
  }
  public set delegatedSubnetId(value: string | undefined) {
    this.inputs['delegated_subnet_id'] = value;
  }
  public get diagnosticSettings(): any | undefined {
    return this.inputs['diagnostic_settings'] as any | undefined;
  }
  public set diagnosticSettings(value: any | undefined) {
    this.inputs['diagnostic_settings'] = value;
  }
  public get enableTelemetry(): boolean | undefined {
    return this.inputs['enable_telemetry'] as boolean | undefined;
  }
  public set enableTelemetry(value: boolean | undefined) {
    this.inputs['enable_telemetry'] = value;
  }
  public get firewallRules(): any | undefined {
    return this.inputs['firewall_rules'] as any | undefined;
  }
  public set firewallRules(value: any | undefined) {
    this.inputs['firewall_rules'] = value;
  }
  public get geoRedundantBackupEnabled(): boolean | undefined {
    return this.inputs['geo_redundant_backup_enabled'] as boolean | undefined;
  }
  public set geoRedundantBackupEnabled(value: boolean | undefined) {
    this.inputs['geo_redundant_backup_enabled'] = value;
  }
  public get highAvailability(): any | undefined {
    return this.inputs['high_availability'] as any | undefined;
  }
  public set highAvailability(value: any | undefined) {
    this.inputs['high_availability'] = value;
  }
  public get location(): string {
    return this.inputs['location'] as string;
  }
  public set location(value: string) {
    this.inputs['location'] = value;
  }
  public get lock(): any | undefined {
    return this.inputs['lock'] as any | undefined;
  }
  public set lock(value: any | undefined) {
    this.inputs['lock'] = value;
  }
  public get maintenanceWindow(): any | undefined {
    return this.inputs['maintenance_window'] as any | undefined;
  }
  public set maintenanceWindow(value: any | undefined) {
    this.inputs['maintenance_window'] = value;
  }
  public get managedIdentities(): any | undefined {
    return this.inputs['managed_identities'] as any | undefined;
  }
  public set managedIdentities(value: any | undefined) {
    this.inputs['managed_identities'] = value;
  }
  public get name(): string {
    return this.inputs['name'] as string;
  }
  public set name(value: string) {
    this.inputs['name'] = value;
  }
  public get pointInTimeRestoreTimeInUtc(): string | undefined {
    return this.inputs['point_in_time_restore_time_in_utc'] as string | undefined;
  }
  public set pointInTimeRestoreTimeInUtc(value: string | undefined) {
    this.inputs['point_in_time_restore_time_in_utc'] = value;
  }
  public get privateDnsZoneId(): string | undefined {
    return this.inputs['private_dns_zone_id'] as string | undefined;
  }
  public set privateDnsZoneId(value: string | undefined) {
    this.inputs['private_dns_zone_id'] = value;
  }
  public get privateEndpoints(): any | undefined {
    return this.inputs['private_endpoints'] as any | undefined;
  }
  public set privateEndpoints(value: any | undefined) {
    this.inputs['private_endpoints'] = value;
  }
  public get privateEndpointsManageDnsZoneGroup(): boolean | undefined {
    return this.inputs['private_endpoints_manage_dns_zone_group'] as boolean | undefined;
  }
  public set privateEndpointsManageDnsZoneGroup(value: boolean | undefined) {
    this.inputs['private_endpoints_manage_dns_zone_group'] = value;
  }
  public get publicNetworkAccessEnabled(): boolean | undefined {
    return this.inputs['public_network_access_enabled'] as boolean | undefined;
  }
  public set publicNetworkAccessEnabled(value: boolean | undefined) {
    this.inputs['public_network_access_enabled'] = value;
  }
  public get replicationRole(): string | undefined {
    return this.inputs['replication_role'] as string | undefined;
  }
  public set replicationRole(value: string | undefined) {
    this.inputs['replication_role'] = value;
  }
  public get resourceGroupName(): string {
    return this.inputs['resource_group_name'] as string;
  }
  public set resourceGroupName(value: string) {
    this.inputs['resource_group_name'] = value;
  }
  public get roleAssignments(): any | undefined {
    return this.inputs['role_assignments'] as any | undefined;
  }
  public set roleAssignments(value: any | undefined) {
    this.inputs['role_assignments'] = value;
  }
  public get serverConfiguration(): any | undefined {
    return this.inputs['server_configuration'] as any | undefined;
  }
  public set serverConfiguration(value: any | undefined) {
    this.inputs['server_configuration'] = value;
  }
  public get serverVersion(): string | undefined {
    return this.inputs['server_version'] as string | undefined;
  }
  public set serverVersion(value: string | undefined) {
    this.inputs['server_version'] = value;
  }
  public get skuName(): string | undefined {
    return this.inputs['sku_name'] as string | undefined;
  }
  public set skuName(value: string | undefined) {
    this.inputs['sku_name'] = value;
  }
  public get sourceServerId(): string | undefined {
    return this.inputs['source_server_id'] as string | undefined;
  }
  public set sourceServerId(value: string | undefined) {
    this.inputs['source_server_id'] = value;
  }
  public get storageMb(): number | undefined {
    return this.inputs['storage_mb'] as number | undefined;
  }
  public set storageMb(value: number | undefined) {
    this.inputs['storage_mb'] = value;
  }
  public get storageTier(): string | undefined {
    return this.inputs['storage_tier'] as string | undefined;
  }
  public set storageTier(value: string | undefined) {
    this.inputs['storage_tier'] = value;
  }
  public get tags(): { [key: string]: string } | undefined {
    return this.inputs['tags'] as { [key: string]: string } | undefined;
  }
  public set tags(value: { [key: string]: string } | undefined) {
    this.inputs['tags'] = value;
  }
  public get timeouts(): any | undefined {
    return this.inputs['timeouts'] as any | undefined;
  }
  public set timeouts(value: any | undefined) {
    this.inputs['timeouts'] = value;
  }
  public get virtualEndpoint(): any | undefined {
    return this.inputs['virtual_endpoint'] as any | undefined;
  }
  public set virtualEndpoint(value: any | undefined) {
    this.inputs['virtual_endpoint'] = value;
  }
  public get zone(): string | undefined {
    return this.inputs['zone'] as string | undefined;
  }
  public set zone(value: string | undefined) {
    this.inputs['zone'] = value;
  }
  public get databaseNameOutput() {
    return this.getString('database_name')
  }
  public get databaseResourceIdsOutput() {
    return this.getString('database_resource_ids')
  }
  public get fqdnOutput() {
    return this.getString('fqdn')
  }
  public get nameOutput() {
    return this.getString('name')
  }
  public get privateEndpointsOutput() {
    return this.getString('private_endpoints')
  }
  public get resourceIdOutput() {
    return this.getString('resource_id')
  }
  protected synthesizeAttributes() {
    return this.inputs;
  }
}
