// generated by cdktf get
export * as resource from './resource';
export * as resourceAction from './resource-action';
export * as updateResource from './update-resource';
export * as dataAzapiResource from './data-azapi-resource';
export * as dataAzapiResourceAction from './data-azapi-resource-action';
export * as provider from './provider';

